Add ability to subclass from both Input and Output allowing for passthrough IO
argoproj-labs/hera pull request #1109
Opened 2024-06-20 14:46 UTC by elliotgunton

**Pull Request Checklist**
- [x] Fixes #922 
- [x] Tests added
- [x] Documentation/examples added
- [x] [Good commit messages](https://cbea.ms/git-commit/) and/or PR title

**Description of PR**
This PR makes it possible to subclass `Input` and `Output` for the new decorators in HEP0001, and then pass an output from a script template call directly into the next step or task. i.e. instead of

```py
@w.dag()
def my_dag():
    output_task = give_output()
    take_input(
        PassthroughIO(
            my_str=output_task.my_str,
            my_int=output_task.my_int,
            my_artifact=output_task.my_artifact,
        )
    )
```
you can do
```py
@w.dag()
def my_dag():
    output_task = give_output()
    take_input(output_task)
```

Note this functionality is limited to script-decorated functions only for now, as other template types would need an even more involved approach where this code had already become complex enough, as we are reconstructing an `Output` from a step or task object.

2024-06-20 14:48 UTC, elliotgunton commented on Makefile
> +	@git diff --exit-code || echo "Code is not up-to-date. Please run 'make codegen'" && exit 1
Changed this so we stop missing non-regenerated examples in CI e.g. for #1108 - https://github.com/argoproj-labs/hera/actions/runs/9566065952/job/26370421288 - had the `Code is not up-to-date. Please run 'make codegen'` message but no failure

2024-06-21 07:20 UTC, samj1912 requested changes
I would prefer if we stay consistent with the functionality around our new templates. I think this will cause a lot of confusion if it only works for script templates, no that they look exactly the same as other templates. Also how would this work for script template stubs?

2024-06-21 08:03 UTC, elliotgunton commented
>I think this will cause a lot of confusion if it only works for script templates

Fair point, I wanted to see if it was possible for script templates first. As for stubs it should work fine as long as they are decorated as script templates - we only need the signature, which is why it's fairly easy to do for script templates as we can access `template.source`. Haven't looked into other template types extensively

2024-06-21 08:48 UTC, elliotgunton commented on Makefile
> +	@git diff --exit-code || echo "Code is not up-to-date. Please run 'make codegen'" && exit 1
Moved to #1110

2024-08-27 15:59 UTC, elliotgunton commented
Closing this as stale and it's only a POC which isn't high priority for now

2024-08-27 15:59 UTC, closed without merging